### ISSUE TITLE
Only lists one device

### ISSUE THREAD

**Issue by wendelit** [badfortrains/spotcontrol#1]
This might just be me not really understanding the Spotify connect protocol but when i run the "devices" command i only get one device (my computer). But i want to play the music from an other Spotify connect app that is on the network (this shows upp in Spotify on my computer). Is this possible ?

**Comment by marcaddeo** [comment]
I thought I had created this same issue! 

I'm having the same problem, spotcontrol doesn't pick up my Denon HEOS devices. But does pick up my computer and phone. 

What kind of device are you trying to control?

**Comment by wendelit** [comment]
I'm trying to play to the Gramofon (gramofon.com)

**Comment by marcaddeo** [comment]
That's what I suspected! Looks like spotcontrol isn't picking up third party devices, but only official spotify clients.

I haven't had a chance to look into the code on this project to try and find out what's going on yet...

**Comment by wendelit** [comment]
I think you are right. I've tried to look in to the code  abit and i think there will have to be writen some code to check for broadcast of these devices. There dose exist a project that fully implements a Spotify connect server and based on that it should be possible to write code for sending to these devices as well.

**Comment by badfortrains** [comment]
I added a new branch that changes the mercury subscription channel and might make your devices show up https://github.com/badfortrains/spotcontrol/tree/devices.

It seems that different devices only listen on certain mercury urls.  The way the protocol works is a device sends out a "hello" message to the channel, then each device on the channel sends out a response "notify" message that contains the device state.

If changing the channel url works, the next step will probably be sending out hello messages on a couple different channels then keeping track of what channel to communicate to each device on.

**Comment by badfortrains** [comment]
Looked into this more and it seems like adding the extra channel url is not enough.  
It seems that connect devices need to be activated via Zeroconf, then commands can be sent normally via the mercury channel as I described above.  I'm testing on a Denon s9000w that has spotify connect, but  might apply to other devices too.

The actual zeroconf interaction is described in the [librespot project docs](https://github.com/plietar/librespot/blob/master/docs/authentication.md#zeroconf-based-authentication).  It seems whenever I click on the choose device icon in the spotify desktop app it sends out a `getInfo` command to the `_spotify-connect._tcp` service.  Then when I actually select the device it issues an `addUser` command which turns the device on and allows the mercury channel interactions.

If your device is like mine once you start controlling it from the official Spotify app, it should show up in spotcontrol and allow control from there too.

**Comment by marcaddeo** [comment]
Hey @badfortrains,

Thanks for looking into this for us! Glad you were able to make some headway.

I have a question though, how are you figuring out what the desktop app is sending out? I'd love to be able to help and contribute but a little lost as to where to begin (doesn't help that I don't know Go and haven't put much time into research yet :smile:).

But this is a topic that interests me and I plan to put more time into it. Currently I'm building out an [Api Client for HEOS](https://github.com/marcaddeo/ex_heos) in Elixir to interface with that. But definitely would want to be able to do the spotify connect stuff!

**Comment by badfortrains** [comment]
For the stuff above I used a [zeroconf browser](http://www.tildesoft.com/) to get the `spotify-connect._tcp` service ip address/port then used wireshark to see what was being sent to that.

Once the device connects to Spotify all the communication is done through the mercury channel, which is encrypted so harder to snoop on.  To understand what's going on there, I've mostly just looked at https://github.com/plietar/librespot.  Librespot implements a functional Spotify connect device that you can connect to from the desktop app, so it's pretty easy to add some print statements to librespot and see what the desktop app is sending over.  Also looking at the spirc proto file will give you a pretty good overview of what communication is going to look like.

If golang isn't your cup of tea @plietar is adding a c binding to librespot so you could alternatively use that (or interface directly in rust).  There is a chat link on the librespot repo (https://gitter.im/sashahilton00/spotify-connect-resources) where people discuss librespot / the spotify connect protocol.  Definitely would check out librespot in general.  Plietar has put in all the hard work reverse engineering the protocol, and the project seems to be making quick progress.

**Comment by plietar** [comment]
When your subscribe to a mercury channel, you get a confirmation message with all the aliased names messages could arrive on. You don't need to subscribe again. Just don't ignore messages from these channels

In librespot it is handled by the `complete_subscription` in  https://github.com/plietar/librespot/blob/master/src/mercury.rs#L130

I'll try and push all the scripts I use to snoop the protocol sometime soon

The C API will only expose the same API as libspotify (it's only got a tiny fraction of it for now)

**Comment by badfortrains** [comment]
Thanks for the clarification plietar, I'll take a look at that.  

Also, releasing the scripts sounds great would definitely be interested in taking a look

**Comment by wendelit** [comment]
Sorry if this question has been answered but is there any code that will that enables us to control Spotify connect devices ?

Thanks for all the answers!

**Comment by marcaddeo** [comment]
@wendelit well.. that's what this library is for :stuck_out_tongue:

**Comment by wendelit** [comment]
@marcaddeo Yes, but the problem that we where looking into here was that you can only see computers and cellphones and not Spotify connect devices :P

**Comment by Crille1** [comment]
Hi, any clues on how to make this code see all devices?
(I just tried and only see my PC)

**Comment by badfortrains** [comment]
Just pushed an update to add mdns discovery, which should hopefully make the missing devices show up.
For it to work you need to:
1. Start spotcontrol in discover mode `./spotcontrol_example --blobPath ./blob`
   (blobPath specifies where the login blob will be cached)
2. Open the spotify desktop/mobile app.  Click connect to device, "spotcontol" should be in the list of available devices.  Connect to it.
3. Spotcontrol should show that it authenticated, and list available commands.  Enter `mdns` command.  Missing devices should be listed.  Select one, spotcontrol will attempt to send the login command to the device.
4. The device should now appear in the devices list in spotcontrol and should be controllable like the desktop app.

**Comment by wendelit** [comment]
Thanks @badfortrains Worked beautifully. tho I did not have to do 1-3 as soon as i started it and entered devices it found my device and could start playing. I'm using the gramofon just for reference.

**Comment by marcaddeo** [comment]
I didn't have to do steps 1-3 either, `list` showed my Heos devices properly!

I just ran it as: `./spotcontrol_example --username <user> --password <pass> --appkey path/to/spotify.key` and did `list`

**Comment by badfortrains** [comment]
Cool glad it works.  It was probably the added Mercury channel that made it show up.

Steps 1-3 are only necessary if the connect device isn't already authenticated with your user account.  So basically connecting to the device on the spotify mobile/desktop app does the same thing that steps 1-3 do.

**Comment by Crille1** [comment]
Thanks @badfortrains , just tried the updated code and it works, great work!
A question: Is it possible to play playlist and albums? I tried to load those IDs but it didnt work for me.

**Comment by badfortrains** [comment]
It seems that there isn't a specific way to queue albums and Playlists with Spotify connect, they are simply treated as a list of tracks.  So the way to add an album would be to get the list of tracks in the album then queue all of them.  There is a field for a context uri which is populated with the album id when spotify queues an album but it still passes in all the tracks.  Will have to look into it more to see how / if the context uri is actually used.

**Comment by ChrisBrandhorst** [comment]
Hi @badfortrains, thanks for your work. I have a Marantz NR1605 which does not show up in the devices list. It is found through the mdns command, but when I select it, it is not added to the devices list. See below. "Blackbox II" is my desktop Mac. Any ideas?

```
$ ./micro-controller --appkey ~/Downloads/spotify_appkey.key --blobPath ./blob
2016/04/09 22:00:36 [ERR] mdns: Failed to bind to udp6 port: listen udp6 [::]:5353->ff02::fb: setsockopt: can't assign requested address
Found a device &{eDMP32MB_2368DB._spotify-connect._tcp.local. Marantz-NR1605.local. 10.1.1.165 <nil> 80 VERSION=1.0|CPath=/goform/spotifyConfig [VERSION=1.0 CPath=/goform/spotifyConfig] 10.1.1.165 true true}
devices [{http://10.1.1.165:80/goform/spotifyConfig eDMP32MB_2368DB}]
2016/04/09 22:00:37 [INFO] mdns: Closing client {0xc820090030 0xc820090038 0xc820090040 <nil> true 0xc82013d620 {1 0}}
2016/04/09 22:00:37 [ERR] mdns: Failed to read packet: read udp4 0.0.0.0:56674: use of closed network connection
2016/04/09 22:00:37 [ERR] mdns: Failed to read packet: read udp6 [::]:56675: use of closed network connection
2016/04/09 22:00:37 [ERR] mdns: Failed to read packet: read udp4 0.0.0.0:5353: use of closed network connection
do login LljCmCqumW6+lEtljwhm3vdUHRI=
Authentication succeedded:  chrisbrandhorst

Available commands:
load <track1> [...more tracks]: load tracks by spotify base 62 id
hello:                          ask devices to identify themselves
play:                           play current track
pause:                          pause playing track
prev:                           play previous track
next:                           play next track
devices:                        list availbale devices
mdns:                           show devices found via zeroconf, and login on device

help:                           show this list

Enter a command: kMessageTypeNotify Blackbox II f71d6030d4426506057bd3eeda7aea8fe96bedb1 13 1460231602116 [LljCmCqumW6+lEtljwhm3vdUHRI=] 
devices

 choose a device:
0) Blackbox II f71d6030d4426506057bd3eeda7aea8fe96bedb1 
Enter device number: 0
Enter a command: mdns

 choose a device:
0) [mdns]eDMP32MB_2368DB http://10.1.1.165:80/goform/spotifyConfig 
Enter device number: 0
start get
resposne &{200 OK 200 HTTP/1.0 1 0 map[Content-Type:[application/json; charset=utf-8] Content-Length:[341] Server:[GoAhead-Webs] Connection:[close]] 0xc8201e2680 341 [] true map[] 0xc8201be7e0 <nil>}
got map[status:101 statusString:ERROR-OK spotifyError:0] &{200 OK 200 HTTP/1.0 1 0 map[Server:[GoAhead-Webs] Connection:[close] Content-Type:[application/json; charset=utf-8] Content-Length:[63]] 0xc820232080 63 [] true map[] 0xc820267960 <nil>} <nil>
Enter a command: devices

 choose a device:
0) Blackbox II f71d6030d4426506057bd3eeda7aea8fe96bedb1 
Enter device number: 
```

**Comment by badfortrains** [comment]
Looks like there is an issue with mdns login  (sending the extracted blob to the Marantz NR1605). 
A couple questions that might help debug it
1.  If you open http://10.1.1.165/goform/spotifyConfig?action=getInfo in your browser what do you see?
2.  If you start the micro-controller and see "Authentication succeedded"  (as you did above) and leave it running, then use the spotify desktop app to play music to Marantz NR1605 does the Marantz NR1605 start to appear in the micro-controller device list?

**Comment by ChrisBrandhorst** [comment]
Btw: Chromecast is wireless, Marantz is wired, Chromecast is in the Marantz. Standby networking is enabled on the Marantz. Funny thing, the Chromecast only shows up on my iPhone.

1:

```
{"status":101,"statusString":"ERROR-OK","spotifyError":0,"spotifyErrorString":"No error","version":"1.3.0","deviceID":"00:06:78:23:68:DB","maxUsers":1,"remoteName":"Marantz NR1605","activeUser":"chrisbrandhorst","publicKey":"bbnxZUQpUj5PHHqYwyWwA5fmviPxCiG0bIOZdd2fwohJsqKNHLo1lqI/VmZCeBOsQV6qsS5GlDN2o/66XF+FvQeLki9N9SysNQKvxbrokgf68EaSPpz+SeHEwfKVNdQh"}
```

2: Yes, that is the case. This btw also holds true for my Chromecast (of which I have been unable to find the correct path to get the response above.

The first time I tried it today, the Marantz showed up immediately in the devices list (it was off), even without having to input the mdns command. This behavior was replicated on both a laptop (wireless) and desktop (wired), but only one time.

After I turn the Marantz off and restart the micro-controller, it is gone again and stays gone until I select it from the Spotify app again.

**Comment by badfortrains** [comment]
Re chromecast: It seems behave differently from other connect devices, need to look into that more.

Wired vs wireless shouldn't make a difference as long as they're both on the same network.  
Could you try one more thing:
1.  Complete the same steps you posted above (start in discovery mode, use mdns command, choose eDMP32MB_2368DB).
2.  After it prints out the " statusString:ERROR-OK spotifyError:0" response try entering the "hello" command.  It might be that the device authenticates correctly with spotify, but doesn't immediately broadcast it's state.

**Comment by plietar** [comment]
I believe the chromecast uses a different authentication mechanism, but I don't own one (yet) so I can't look into that.
Once you activate it with your phone, it should appear here though.

**Comment by ChrisBrandhorst** [comment]
@plietar Correct.

-- edit, I read it wrong --
@badfortrains following your steps after removing the saved blob, I get:

```
$ ./micro-controller --blobPath ./blob --appkey ~/Downloads/spotify_appkey.key
start discoverable
got request:  getInfo
got request:  resetUsers
got request:  addUser
do login LljCmCqumW6+lEtljwhm3vdUHRI=
Authentication succeedded:  chrisbrandhorst

Available commands:
load <track1> [...more tracks]: load tracks by spotify base 62 id
hello:                          ask devices to identify themselves
play:                           play current track
pause:                          pause playing track
prev:                           play previous track
next:                           play next track
devices:                        list availbale devices
mdns:                           show devices found via zeroconf, and login on device

help:                           show this list

Enter a command: got request:  getInfo
kMessageTypeNotify Blackbox II f71d6030d4426506057bd3eeda7aea8fe96bedb1 4 1460660781593 [LljCmCqumW6+lEtljwhm3vdUHRI=] 
got request:  getInfo
mdns
no devices found
Enter a command: got request:  getInfo
devices

 choose a device:
0) Blackbox II f71d6030d4426506057bd3eeda7aea8fe96bedb1 
Enter device number: 0  
Enter a command: mdns
no devices found
Enter a command: ^C
```

So the Marantz is not found at all...
If after this, I restart the controller:

```
$ ./micro-controller --blobPath ./blob --appkey ~/Downloads/spotify_appkey.key
2016/04/14 21:10:39 [ERR] mdns: Failed to bind to udp6 port: listen udp6 [::]:5353->ff02::fb: setsockopt: can't assign requested address
Found a device &{eDMP32MB_2368DB._spotify-connect._tcp.local. Marantz-NR1605.local. 10.1.1.165 <nil> 80 VERSION=1.0|CPath=/goform/spotifyConfig [VERSION=1.0 CPath=/goform/spotifyConfig] 10.1.1.165 true true}
devices [{http://10.1.1.165:80/goform/spotifyConfig eDMP32MB_2368DB}]
2016/04/14 21:10:40 [INFO] mdns: Closing client {0xc820090030 0xc820090038 0xc820090040 <nil> true 0xc82013b5c0 {1 0}}
2016/04/14 21:10:40 [ERR] mdns: Failed to read packet: read udp4 0.0.0.0:65257: use of closed network connection
2016/04/14 21:10:40 [ERR] mdns: Failed to read packet: read udp6 [::]:65258: use of closed network connection
2016/04/14 21:10:40 [ERR] mdns: Failed to read packet: read udp4 0.0.0.0:5353: use of closed network connection
do login LljCmCqumW6+lEtljwhm3vdUHRI=
Authentication succeedded:  chrisbrandhorst

Available commands:
load <track1> [...more tracks]: load tracks by spotify base 62 id
hello:                          ask devices to identify themselves
play:                           play current track
pause:                          pause playing track
prev:                           play previous track
next:                           play next track
devices:                        list availbale devices
mdns:                           show devices found via zeroconf, and login on device

help:                           show this list

Enter a command: mkMessageTypeNotify Blackbox II f71d6030d4426506057bd3eeda7aea8fe96bedb1 2 1460660781593 [LljCmCqumW6+lEtljwhm3vdUHRI=] 
dns

 choose a device:
0) [mdns]eDMP32MB_2368DB http://10.1.1.165:80/goform/spotifyConfig 
Enter device number: 0
start get
resposne &{200 OK 200 HTTP/1.0 1 0 map[Connection:[close] Content-Type:[application/json; charset=utf-8] Content-Length:[341] Server:[GoAhead-Webs]] 0xc820431e80 341 [] true map[] 0xc8204760e0 <nil>}
got map[status:101 statusString:ERROR-OK spotifyError:0] &{200 OK 200 HTTP/1.0 1 0 map[Server:[GoAhead-Webs] Connection:[close] Content-Type:[application/json; charset=utf-8] Content-Length:[63]] 0xc8202f60c0 63 [] true map[] 0xc8202821c0 <nil>} <nil>
Enter a command: hello
Enter a command: kMessageTypeHello  LljCmCqumW6+lEtljwhm3vdUHRI= 2 0 [] 
kMessageTypeNotify Blackbox II f71d6030d4426506057bd3eeda7aea8fe96bedb1 3 1460660781593 [LljCmCqumW6+lEtljwhm3vdUHRI=] 
devices

 choose a device:
0) Blackbox II f71d6030d4426506057bd3eeda7aea8fe96bedb1 
Enter device number: 
```

So no Marantz in the list and no response after the hello.
Once I select the Marantz from the desktop app, it shows up in the devices list. If, in this state, I repeat the steps, the Marantz sends a Goodbye when selecting it from the mdns list.

```
Enter a command: kMessageTypeHello Blackbox II f71d6030d4426506057bd3eeda7aea8fe96bedb1 58 1460661176457 [] 
kMessageTypeHello Marantz NR1605 00:06:78:23:68:DB 1 0 [] 
kMessageTypeNotify Blackbox II f71d6030d4426506057bd3eeda7aea8fe96bedb1 1 1460661176457 [00:06:78:23:68:DB] 
kMessageTypeLoad Blackbox II f71d6030d4426506057bd3eeda7aea8fe96bedb1 2 0 [00:06:78:23:68:DB] 
kMessageTypeNotify Marantz NR1605 00:06:78:23:68:DB 2 1460661176457 [] 
kMessageTypeNotify Marantz NR1605 00:06:78:23:68:DB 3 1460661220259 [] 
devices

 choose a device:
0) Marantz NR1605 00:06:78:23:68:DB 
1) Blackbox II f71d6030d4426506057bd3eeda7aea8fe96bedb1 
Enter device number: 0
Enter a command: mdns

 choose a device:
0) [mdns]eDMP32MB_2368DB http://10.1.1.165:80/goform/spotifyConfig 
Enter device number: 0
kMessageTypeGoodbye Marantz NR1605 00:06:78:23:68:DB 4 1460661220259 [] 
start get
resposne &{200 OK 200 HTTP/1.0 1 0 map[Content-Type:[application/json; charset=utf-8] Content-Length:[341] Server:[GoAhead-Webs] Connection:[close]] 0xc820220800 341 [] true map[] 0xc8204221c0 <nil>}
got map[status:101 statusString:ERROR-OK spotifyError:0] &{200 OK 200 HTTP/1.0 1 0 map[Server:[GoAhead-Webs] Connection:[close] Content-Type:[application/json; charset=utf-8] Content-Length:[63]] 0xc820220940 63 [] true map[] 0xc82041f340 <nil>} <nil>
Enter a command: hello
Enter a command: kMessageTypeHello  LljCmCqumW6+lEtljwhm3vdUHRI= 5 0 [] 
kMessageTypeNotify Blackbox II f71d6030d4426506057bd3eeda7aea8fe96bedb1 1 1460661220259 [LljCmCqumW6+lEtljwhm3vdUHRI=] 
```

BTW: could the mdns error on top be influencing this?

**Comment by ChrisBrandhorst** [comment]
OK, I think I found it! In `discovery.go`, your username is hardcoded, @badfortrains.
If I change it to my own, everything works well. I'll make a PR for this.

See PR: https://github.com/badfortrains/spotcontrol/pull/3

**Comment by badfortrains** [comment]
Doh :( well that's embarrassing.  Glad you figured it out though 👍  
Will take a look at the pr tonight.

**Comment by plietar** [comment]
@badfortrains I've just pushed some of the stuff I use to analyze the protocol https://github.com/plietar/spotify-analyze

Lets you dump the packets exchanged  by the desktop client, and view it in wireshark

**Comment by badfortrains** [comment]
Wow super cool @plietar!  Thanks for sharing, looking forward to checking it out over the weekend.
