### ISSUE TITLE
[Feature Request] Micro-Controller: Select device by Name/Ident

### ISSUE THREAD

**Issue by valentingc** [badfortrains/spotcontrol#11]
Hello,

I am requesting the feature to select a device by Name or by Ident instead of the array number (1,2,3,...).
The origin of this request is that I am trying to automate a pause/play function via a dash button, but every time I launch spotcontrol the list has another order, so it's impossible to pick the same device every time.

Thanks a lot!

**Comment by badfortrains** [comment]
Added a command line flag to specify ident:

````
./micro-controller --username SPOTIFY_USERNAME --password SPOTIFY_PASSWORD --ident 123121232342323423
````
