### ISSUE TITLE
[Feature request] Load a playlist

### ISSUE THREAD

**Issue by jared-94** [badfortrains/spotcontrol#5]
Hi,

Thanks for your great software!
I am able to load a track or list of tracks, but I would like to load a Spotify playlist...

Is it possible?

**Comment by wendelit** [comment]
Hallo,
To do this i think you have to use the spotify API https://developer.spotify.com/web-api/ to get the IDs of the track in the playlist and than load them. That is how i did it at least.

**Comment by badfortrains** [comment]
Added some basic support for this, still cleaning it up so leaving it on a separate branch for now (https://github.com/badfortrains/spotcontrol/tree/playlistMaster).  You can give it a shot.

Added a `playlist` command to load a playlist by id in the micro-controller example.
`playlist 2BMC7aZVCrWgcSSV4eLLtt` loads playlist with id 2BMC7aZVCrWgcSSV4eLLtt

**Comment by jared-94** [comment]
Thank you it works fine!

I can now load a personal playlist, but not playlist provided by spotify, for instance :
https://play.spotify.com/user/sonymusicentertainment/playlist/3oRNodhtGLVnZl0Q32FJHB

I think it's because it's not the same user...

**Comment by jared-94** [comment]
Ok I managed it with the following modification (adding an optional thrid argument):
file main.go:
`case cmds[0] == "playlist":
            var user = ""
            if (len(cmds) > 2) {
              user = cmds[2]
            }
            playlist, err := sController.GetPlaylist(cmds[1], user)`

file metadata.go:
`func (c *SpircController) GetPlaylist(id string, user string) (*Spotify.SelectedListContent, error) {
    if (user == "") {
      user = c.username
    }
    url := "hm://playlist/user/" + user + "/playlist/" + id`

**Comment by badfortrains** [comment]
Ah didn't think about playlist from other users.  I just pushed a change to the branch that
1.  Makes `playlist` command take a full id (eg `user/sonymusicentertainment/playlist/3oRNodhtGLVnZl0Q32FJHB`)
2. Adds a `rootlist` command that lists all playlists the current user has

**Comment by jared-94** [comment]
Great! Thanks!!
