### ISSUE TITLE
Error with mdns command

### ISSUE THREAD

**Issue by jared-94** [badfortrains/spotcontrol#6]
Hi,

When running mdns command I get the following error:

`mdns
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x98ea4]

goroutine 1 [running]:
panic(0x34c1f0, 0x10826008)
        /usr/local/go/src/runtime/panic.go:500 +0x33c
github.com/badfortrains/spotcontrol.(*SpircController).ListMdnsDevices(0x10ab81e0, 0x0, 0x0, 0x0)
        /home/pi/go/src/github.com/badfortrains/spotcontrol/spirc_controller.go:135 +0x44
main.addMdns(0x10ab81e0, 0x1084ff44)
        /home/pi/go/src/github.com/badfortrains/spotcontrol/examples/micro-controller/main.go:48 +0x38
main.main()
        /home/pi/go/src/github.com/badfortrains/spotcontrol/examples/micro-controller/main.go:144 +0x8c8
`

Is this specific to my config?
Thanks

**Comment by badfortrains** [comment]
The mdns command only works when micro-controller is started in discovery mode:
`micro-controller --blobPath ./some-path-to-save-a-blob-to`

It needs to extract a mdns login blob from a spotify client so it can send the blob to other spotify-connect clients.

**Comment by jared-94** [comment]
OK thank you it works fine !
