### ISSUE TITLE
App key not needed anymore

### ISSUE THREAD

**Issue by kalj** [badfortrains/spotcontrol#8]
Now that the spotify app key is not needed anymore, can that requirement be removed somehow?

**Comment by badfortrains** [comment]
Done, updated the login code so it's not needed anymore.
https://github.com/badfortrains/spotcontrol/commit/d5c6f7d53922db1b605aa5674839c44798c2e748

Fix based on: https://github.com/plietar/librespot/commit/4cca541339a5b722b6985dcc716fcbf9dc9e6b5f
